# Generated by Django 4.0 on 2021-12-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=100, null=True)),
                ('director_name', models.CharField(max_length=100, null=True)),
                ('actor_1_name', models.CharField(max_length=100, null=True)),
                ('actor_2_name', models.CharField(max_length=100, null=True)),
                ('actor_3_name', models.CharField(max_length=100, null=True)),
                ('genres', models.CharField(max_length=100, null=True)),
                ('imdb_score', models.PositiveIntegerField(null=True)),
                ('budget', models.PositiveIntegerField(null=True)),
                ('gross', models.PositiveIntegerField(null=True)),
                ('profit_percent', models.PositiveIntegerField(null=True)),
                ('predictions', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
